name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Any screenshots, API endpoints, or use cases.
